pipeline {
    agent any
    stages{
        stage('Cpu details'){
            steps{
                sh '''
                    echo "Building cpu details"
                    lscpu
                '''
            }
        }
        stage('Build system details'){
            steps{
                sh '''
                    echo "System details 1-stage"
                    uname -a
                '''
            }
        }
        stage('Memory details'){
            steps{
                sh '''
                    echo "Printing memory details"
                    free -h

                '''
            }
        }
        stage('Current date'){
            steps{
                sh '''
                    echo "Printing current date"
                    date

                '''
            }
        }
    }
}